### ISSUE TITLE
LESS: Function and argument Rgba doesn't work

### ISSUE THREAD

**Issue by ianberdin** [livestyle/issues#1]
work:   `less .box-shadow(0 1px 4px #00000);`
doesn't work: `less.box-shadow(0 1px 4px rgba(0, 0, 0, 1));`

``` less
.box-shadow(@arguments) {
  -webkit-box-shadow: @arguments;
  -moz-box-shadow: @arguments;
  box-shadow: @arguments;
}
```
