### ISSUE TITLE
Check selector duplication issue

### ISSUE THREAD

**Issue by sergeche** [livestyle/issues#11]
Try the following CSS

``` css
.foo {color: red;}
.bar {color: blue;}
```
1. Copy selector `.foo`
2. Create new line after `.bar`
3. Paste copied selector
4. Rename pasted selector to `.baz`

The original `.foo` selector might disappear from DevTools
