### ISSUE TITLE
Unable to pass variables to mixin parameters

### ISSUE THREAD

**Issue by ethaksus** [livestyle/issues#127]
I've notice that LS's processor is unable to pass variables into mixins and then generates the rules wrong. 

SCSS Input:

``` scss
$c: red;

@mixin foo($a) {
color: $a;
}

.bar {
@include foo($c);
}
```

CSS Output:

``` css
.bar {
color: $a;
}
```

While it _should_ output:

``` css
.bar {
color: red;
}
```
