### ISSUE TITLE
[analyzer] No mixin output widget in mixin call with content

### ISSUE THREAD

**Issue by sergeche** [livestyle/issues#128]
Example:

``` scss
$color: white;
@mixin colors($color: blue) {
  background-color: $color;
  @content;
  border-color: $color;
}
.colors {
  @include colors { color: $color; }
}
```
