### ISSUE TITLE
Support `@function` directive in SCSS

### ISSUE THREAD

**Issue by micahgodbolt** [livestyle/issues#15]
livestyle currently supports displaying the output of some color functions, but it doesn't supporting the same for functions like str-length etc. 

It would also be great to see support for custom functions

``` scss
@function myfunc(i) {
  @return i + 1;
}

div {
  line-height: myfunc(1); // shows a return of 2
}

```

![screenshot 2015-03-26 08 58 55](https://cloud.githubusercontent.com/assets/1434956/6850438/7ad0b6c6-d396-11e4-98de-ca44c4536e37.png)
