### ISSUE TITLE
LESS: Add support @proccess (scripting)

### ISSUE THREAD

**Issue by ianberdin** [livestyle/issues#2]
Code for tests: http://lesshat.madebysource.com/ (mixins)

**Comment by sergeche** [comment]
Fixed, please update Chrome extension.

**Comment by ianberdin** [comment]
http://take.ms/cM95u
LiveStyle: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to parse the rule '.p-lessons .p-lessons_cnt . .p-lessons_cnt_i.__disabled {}'.

https://gist.github.com/happierall/5c5b5558cd83e3c8e692

**Comment by sergeche** [comment]
You’ll see such warnings occasionally when typing new selectors. Because `.p-lessons .p-lessons_cnt . .p-lessons_cnt_i.__disabled` is not a valid selector, browser can’t create such rule

**Comment by ianberdin** [comment]
Please see in the source code. It is work for default preprocessor.

**Comment by sergeche** [comment]
Please create a separate issue. This one is not related to JS scripting

**Comment by ianberdin** [comment]
Doesn't work.
Screen: http://take.ms/wQhCv
Lib: Lesshat
code: 

``` less
@import "lesshat";
div {
    background: #faf;
    width: 255px;
    height: 125px;
    margin: 205px;
    .border-radius(10px);
}
```

``` javascript
settings:
{
    "settings": {
        "livestyle": {
            "globals": ["./lesshat.less",]
        }
    },
}
```
