### ISSUE TITLE
Wrong editor file patching

### ISSUE THREAD

**Issue by sergeche** [livestyle/issues#24]
The following CSS is broken when there are incoming updates for `.aion-return-sticker` section:

PS: issues occur for minified and autoprefixed browser CSS

``` css
@font-face {
    font-family: "RomulCWeb";
    src: url("https://st2-ru.4game.com/-/42a9cb58/b/pAionGL/font/romulc.eot");
    src: local("RomulCWeb"),
        url('https://st2-ru.4game.com/-/42a9cb58/b/pAionGL/font/romulc.eot?#iefix') format('embedded-opentype'),
        url('https://st2-ru.4game.com/-/42a9cb58/b/pAionGL/font/romulc.woff') format('woff'),
        url('https://st2-ru.4game.com/-/42a9cb58/b/pAionGL/font/romulc.ttf') format('truetype');
}

.aion-return {
    position: relative;
    background: url(../img/page-bg.jpg) #fff top center no-repeat;
    font-family: arial, sans-serif;
    font-size: 16px;
    line-height: 1.5;
    padding: 60px 0;
    border-bottom-left-radius: 10px;
    border-bottom-right-radius: 10px;
}

.aion-return h1,
.aion-return h2 {
    font-family: RomulCWeb, serif;
    font-weight: normal;
    font-size: 2em;
    text-transform: uppercase;
    letter-spacing: 3px;
    margin-top: 0;
}

.aion-return h1 {
    line-height: 1.2;
    margin-bottom: 0.9em;
}

.aion-return h2 {
    font-size: 1.2em;
}

.aion-return h4 {
    font-family: 'PT Sans', sans-serif;
    font-size: 1.1em;
    color: #495055;
    margin: 0em 0;
}

.aion-return .aion-return-title-action {
    margin: 0 0 -0.8em;
    line-height: 1.3;
    position: relative;
    top: -1.2em;
}

.aion-return-content {
    padding: 0 35px;
    margin: 0 auto;
    max-width: 710px;
    text-align: center;
    margin-top: 50px;
}

.aion-return_activated .aion-return-content {
    margin-top: 20px;
}

.aion-return-content:nth-of-type(1),
.aion-return_activated .aion-return-content:nth-of-type(1) {
    color: #fff;
    margin-top: 0;
}

.aion-return-content_wide {
    max-width: 100%;
}

.aion-return-learn-more {
    color: #ffcd3f;
    text-shadow: 0 1px 4px rgba(0,0,0,0.25);
    text-decoration: none;
}

.aion-return-learn-more:hover {
    color: #f1b200;
}

.aion-return-learn-more:after {
    content: '';
    width: 8px;
    height: 8px;
    display: inline-block;
    border: solid currentColor;
    border-width: 1px 1px 0 0;

    margin-left: 0.3em;
    position: relative;
    /* top: 0.1em; */
    -webkit-transform: rotate(45deg);
    -o-transform: rotate(45deg);
    transform: rotate(45deg);
}

.aion-return-list {
    list-style: none;
    display: block;
    text-align: left;
    width: 69%;
    margin: 1.2em auto;
}

.aion-return-list li {
    position: relative;
}

.aion-return-list li:before {
    content: '—';
    position: absolute;
    margin-left: -1.5em;
}

/* Подарки */
.aion-return-gifts_for-issuer {
    float: left;
    width: 33%;
    margin-right: 35px;
}

.aion-return-gifts_for-issuer .aion-return-gifts__list {
    border-right: 1px solid #e5e5e5;
    text-align: center;
}

.aion-return-gifts_for-issuer .aion-return-gifts__list-item {
    width: auto;
}

.aion-return-gifts__title {
    font-family: RomulCWeb, serif;
    letter-spacing: 2px;
    margin-bottom: 1.5em;
    margin-top: 0;
    -webkit-font-smoothing: subpixel-antialiased;
}

.aion-return-gifts__subtitle {
    font-size: 0.8em;
    line-height: 1.3;
    margin-top: -2em;
    margin-bottom: 0.8em;
}

.aion-return-gifts__list {
    text-align: center;
    display: block;
    list-style-type: none;
    padding: 12px 0 0;
    margin: 0;
    text-align: justify;
    overflow: hidden;
}

.aion-return-gifts__list:after {
    display: inline-block;
    content: '';
    width: 100%;
    height: 0;
}

.aion-return-gifts__list-item {
    display: inline-block;
    width: 110px;
    vertical-align: top;
    font-family: 'PT Sans', sans-serif;
    font-weight: bold;
    font-size: 1.1em;
    line-height: 1.2;
    text-align: center;
    position: relative;
}

.aion-return-gifts__list-image {
    display: block;
    margin: 0 auto;
}

.aion-return-gifts__list-comment {
    display: block;
    font-family: arial, sans-seirf;
    font-weight: normal;
    font-size: 0.7em;
    margin-top: 0.5em;
}

.aion-return-gifts__check {
    display: inline-block;
    position: absolute;
    background: url(data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTciIGhlaWdodD0iMTciIHZpZXdCb3g9IjAgMCAxNyAxNyIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTMuNzc0IDIuNDY0Yy0xLjQ2Ny0xLjQwMS0zLjQzLTIuMjY0LTUuNTc0LTIuMjY0LTQuNSAwLTguMiAzLjgtOC4yIDguNCAwIDQuNiAzLjcgOC40IDguMiA4LjQgNC41IDAgOC4yLTMuOCA4LjItOC40IDAtMS42NzMtLjQ5LTMuMjQxLTEuMzI5LTQuNTU4bC02LjQ3MSA4LjU1OC0uOSAxLjEtLjktMS4yLTMuOS00LjUgMS4zLTIuNiAzLjggMy45IDUuNzc0LTYuODM2eiIgZmlsbD0iIzQ0QTkyNiIvPjwvc3ZnPg==);
    width: 17px;
    height: 17px;
    position: absolute;
    top: 77px;
    left: 90px;
    opacity: 0;

    -webkit-animation: 0.5s ease-in-out;
    animation: 0.5s ease-in-out;

    -webkit-animation-fill-mode: backwards;
    -o-animation-fill-mode: backwards;
    animation-fill-mode: backwards;
}

.aion-return-gifts__list-item:nth-of-type(2) .aion-return-gifts__check {
    -webkit-animation-delay: 0.1s;
    animation-delay: 0.1s;
}

.aion-return-gifts__list-item:nth-of-type(3) .aion-return-gifts__check {
    -webkit-animation-delay: 0.2s;
    animation-delay: 0.2s;
}

.aion-return-gifts__list-item:nth-of-type(4) .aion-return-gifts__check {
    -webkit-animation-delay: 0.3s;
    animation-delay: 0.3s;
}

.aion-return-gifts__list-item:nth-of-type(5) .aion-return-gifts__check {
    -webkit-animation-delay: 0.4s;
    animation-delay: 0.4s;
}

[data-state="code_is_activated_step"] .aion-return-gifts__check {
    opacity: 1;
    -webkit-animation-name: aion-return-check;
    animation-name: aion-return-check;
}

.aion-return-sticker {
    position: absolute;
    top: -2px;
    right: -2px;
    width: 12em;
    height: 12em;
    overflow: hidden;
}

.aion-return-sticker__content {
    color: #fff;
    text-align: center;
    padding: 5px 0;
    font-size: 0.9em;
    position: absolute;
    width: 200%;
    top: 50%;
    left: -50%;
    margin-top: -1.1em;
    background-image: -webkit-linear-gradient(#1ebabf, #1799a2);
    background-image: -o-linear-gradient(#1ebabf, #1799a2);
    background-image: linear-gradient(#1ebabf, #1799a2);
    -webkit-box-shadow: 0 0 2px rgba(0, 0, 0, 0.6);
    box-shadow: 0 0 2px rgba(0, 0, 0, 0.6);

    -webkit-transform: rotate(45deg) translate(0, -50px);
    -ms-transform: rotate(45deg) translate(0, -50px);
    -o-transform: rotate(45deg) translate(0, -50px);
    transform: rotate(45deg) translate(0, -50px);
}

.aion-return-sticker__content a {
    color: inherit;
}

@keyframes aion-return-check {
    from {
        opacity: 0;
        transform: scale(4);
    }

    70% {
        transform: scale(0.7);
    }

    to {
        transform: scale(1);
        opacity: 1;
    }
}

/* Контент для различных состояний активации */
[data-for-state] {
    display: none;
}

[data-state="cant_activate_step"] [data-for-state="cant_activate_step"] {
    display: block;
}
```
