### ISSUE TITLE
Typing new property near inner section might break it

### ISSUE THREAD

**Issue by sergeche** [livestyle/issues#27]
Sometimes, in the following case:

``` scss
foo {
    width: 100px;
    z1 // <-- typing new property with Emmet
    &:after {
        display: block;
    }
}
```

The inner section might get broken in DevTools:

``` css
foo {
    width: 100px;
    &:a;
    z-index: 1;
}

z foo:after {
    display: block;
}
```
