### ISSUE TITLE
Support linear-gradient expressions

### ISSUE THREAD

**Issue by sergeche** [livestyle/issues#29]
Currently, LS throws exception on this example:

``` less
div {
    background: linear-gradient(to bottom, @color 0%, @color 33%, fade(@color, 0.65) 67%, fade(@color, 0) 100%);
}
```

`Unable to evaluate expression "linear-gradient(to bottom, @color 0%, @color 33%, fade(@color, 0.65) 67%, fade(@color, 0) 100%)": Invalid color token: @l2-bg-colo (4)`
