### ISSUE TITLE
Possible parsing error

### ISSUE THREAD

**Issue by sergeche** [livestyle/issues#31]
This CSS can possibly break parsing due to `//` characters:

``` css
div {
    background-image: url('data:image/png;base64,iVBORw0KGgoAAAVEUAAAD////...');
}
```
