### ISSUE TITLE
Colour variables not working properly?

### ISSUE THREAD

**Issue by rob-mcdonald** [livestyle/issues#40]
Including `variables.less` in globals.

``` less
@pink-lighter: lighten(@pink, 80%);
@pink-light: #f885b4;
@pink-dark: #d32f7b;
@pink: mix(@pink-light, @pink-dark, 5%);
```

And `_forms.less`

``` less
.show-validation {

  .form-control {
    &.error {
      background: @pink-lighter;
    }
  }
}
```

![screen shot 2015-08-10 at 14 32 51](https://cloud.githubusercontent.com/assets/13622137/9172614/c0c6212e-3f6c-11e5-8584-785d5a68152d.png)

It may be the order I'm declaring it in, or possibly as there's a lot of colour functions going on there. But, this works (all in same file):

``` less
@red: red;
@red-lighter: lighten(@red, 40%);

.show-validation {

  .form-control {
    &.error {
      background: @red-lighter;
    }
  }
}
```

![screen shot 2015-08-10 at 14 32 59](https://cloud.githubusercontent.com/assets/13622137/9172620/c5ae53d2-3f6c-11e5-91d7-f588eb353091.png)

[log](http://codeshare.io/fBTov)
