### ISSUE TITLE
Bubbled media queries not working properly?

### ISSUE THREAD

**Issue by rob-mcdonald** [livestyle/issues#46]
I'm trying to do the following:

``` less
.slider-promotions-container {
  .clearfix();
  // margin-bottom: 10px;

  @media (max-width: 600px) {
    margin-bottom: 10px;
  }
}
```

And the margin isn't showing up (If I add it outside the mq it works). I think there was a bit of weird behaviour with the `div` losing height, given by the `.clearfix()`, but that's only happened once and could be something else.

[log](http://codeshare.io/Mw8z4)
