### ISSUE TITLE
Invalid expression evaluation

### ISSUE THREAD

**Issue by sergeche** [livestyle/issues#54]
Example:

``` less
@activeYOffset: -72px;
&::after {
    background-position: -138px @activeYOffset;
}
```

emits error `Unable to evaluate expression "-138px -72px": Unexpected number at column 8 in expression -138px -72px`
