### ISSUE TITLE
Wrong updates from DevTools

### ISSUE THREAD

**Issue by sergeche** [livestyle/issues#59]
In the following LESS example:

``` less
.transition() {
    transition-property: opacity, transform;
}

.foo {
    width: 100px;
    .transition();
}
```

when changing `width` property of `.foo` in DevTools, the source LESS then looks as following:

``` less
.foo {
    width: 90px;
    -webkit-transition-property: opacity, -webkit-transform;
    .transition();
}
```

The source was compiled and Autoprefixed.
