### ISSUE TITLE
Debug issue with `:nth-of-type()`

### ISSUE THREAD

**Issue by sergeche** [livestyle/issues#6]
Adding and editing CSS with `:nth-of-type()` causes invalid result in CSSOM. Example:

``` css
.eldorado__preloader-inner:nth-of-type(1) {
    border-width: 1px;
}

.eldorado__preloader-inner:nth-of-type(2) {
    top: 3px;
    right: 3px;
    bottom: 3px;
    left: 3px;
    border-width: 4px;
}

.eldorado__preloader-inner:nth-of-type(3) {
    top: 9px;
    right: 9px;
    bottom: 9px;
    left: 9px;
    border-width: 4px;
}

.eldorado__preloader-inner:nth-of-type(4) {
    top: 15px;
    right: 15px;
    bottom: 15px;
    left: 15px;
    border-width: 1px;
}

.eldorado__preloader-inner:nth-of-type(5) {
    border-width: 8px;
    border-color: rgba(255, 255, 255, 0.2);
    display: none;
}
```
