### ISSUE TITLE
first block of css worked, but second  de-activated first

### ISSUE THREAD

**Issue by smlombardi** [livestyle/issues#82]
I was working on a Wordpress home page for a client. In the HTML, I set up a class for a row and created an H1 and H4 inside the row (see image below).

I opened the style.css file of my Child Theme in Transmit 4.4.10 in Sublime 3095 and associated it in Chrome 49.0.2606.0.  Fine.  I created the css block:

``` css
.home-welcome h1 {
  color: #fff;
}
```

and the first header turned white.  Perfect.

I created a second block:

``` css
.home-welcome h4 {
  color: #fff;
  margin-top: 0;
}
```

And it worked -- **BUT** the first line turned back to the default color. No idea why.

UPDATE:  Subsequent edit went well, and it's blast to use.  Not sure what happened above.

The url is http://www.thevillany.com/ but, as I'm working on it, it might be different when you look at it.

![screen shot 2015-12-29 at 1 14 47 pm](https://cloud.githubusercontent.com/assets/835148/12039492/f777effa-ae2e-11e5-9395-1262fa6a4820.png)
